name: tavrida_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+22

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_extensions: ^2.2.2
  package_info_plus: ^4.2.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  injector: ^3.0.0
  dio: ^5.3.2
  ar_flutter_plugin: ^0.7.3
  path_provider: ^2.1.0
  flutter_archive: ^5.0.0
  intl: ^0.18.1
  gallery_saver: ^2.3.2
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.7
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#262732"
  ios: true
  adaptive_icon_foreground: "assets/logo.png"
  image_path: "assets/logo.png"
  min_sdk_android: 28 # android min sdk min:16, default 21
